PREFIX : <tag:ericmoritz@gmail.com,2015:vocabs/mrs#>


SELECT 
?who ?review ?album ?score ?title ?artist ?normalizedScore
WHERE {
       ?review :album ?album ;
               :rating ?score .

       ?album :title ?title ;
              :artist ?artist .

       ?score :normalizedScore ?normalizedScore .
       OPTIONAL { ?who :seen ?review }
       FILTER ( !bound(?who) || ?who != <http://eric.themoritzfamily.com/> )
       FILTER ( ?normalizedScore >= 80 ) .
}

ORDER BY DESC(?normalizedScore)
LIMIT 10